config/routes.rb
Rails.application.routes.draw do
  resources :users_cards
  devise_for :debits
  devise_for :admins
  devise_for :users

  resources :users
  resources :debits

  post '/signin', to: 'sessions#login'
  delete '/signout', to: 'sessions#logout'

  root 'home#homepage'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/debit.rb
class Debit < ActiveRecord::Base

  validates_presence_of :card_num, :exp_month, :exp_year 

  validates_numericality_of :exp_month, only_integer: true

  validates :exp_month, inclusion: {in: 1..12}

  validates_numericality_of :exp_year, greater_than_or_equal_to: 2015

  validates :card_num, length: {in: 15..16}

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
 
validates_presence_of :email, :password, :fname, :lname

 validates :email, uniqueness: true

 validates :password, length: { minimum: 4 },
confirmation: true

 validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message:" format must be xxx-xxx-xxxx"}

 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :debit
end

app/models/user_card.rb
class UserCard < ActiveRecord::Base
	belongs_to :user
	belongs_to :debit
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
  	session[:id] ? User.find(session[:id]) : nil
  end

end

app/controllers/debits_controller.rb
class DebitsController < ActionController::Base

	def index
		@debits = Debit.all
	end

	def show
		@debits = Debit.all
	end

	def edit
		@debit = Debit.find(params[:id])
	end

	def new
		@debit = Debit.new
	end

	def create
		@debit = Debit.new(debitparams)
		if @debit.save
			flash[:notice] = "Card has been saved!"
			redirect_to users_path
		else
			flash[:alert] = "Card was not saved successfully."
			redirect_to users_path
		end
	end

	private

	def debitparams
		params.require(:debit).permit(:cardnumber, :cardtype, :expirationmonth, :expirationyear)
	end
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def homepage
  	@user = User.new
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ActionController::Base

	def login
		@user = User.find_by(email: params[:email])
		if @user and @user.password == params[:password]
			session[:id] = @user.id
		redirect_to users_path, [:notice] = "Successfully logged in!"
		else
			redirect_to root_path 
			flash[:notice] = "Incorrect login information."
		end
	end	

	def logout
		session[:id] = nil
		flash[:notice] = "You have logged out successfully!"
		redirect_to root_path
	end

end

app/controllers/users_cards_controller.rb
class UsersCardsController < ApplicationController
  before_action :set_users_card, only: [:show, :edit, :update, :destroy]

  # GET /users_cards
  # GET /users_cards.json
  def index
    @users_cards = UsersCard.all
  end

  # GET /users_cards/1
  # GET /users_cards/1.json
  def show
  end

  # GET /users_cards/new
  def new
    @users_card = UsersCard.new
  end

  # GET /users_cards/1/edit
  def edit
  end

  # POST /users_cards
  # POST /users_cards.json
  def create
    @users_card = UsersCard.new(users_card_params)

    respond_to do |format|
      if @users_card.save
        format.html { redirect_to @users_card, notice: 'Users card was successfully created.' }
        format.json { render :show, status: :created, location: @users_card }
      else
        format.html { render :new }
        format.json { render json: @users_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_cards/1
  # PATCH/PUT /users_cards/1.json
  def update
    respond_to do |format|
      if @users_card.update(users_card_params)
        format.html { redirect_to @users_card, notice: 'Users card was successfully updated.' }
        format.json { render :show, status: :ok, location: @users_card }
      else
        format.html { render :edit }
        format.json { render json: @users_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_cards/1
  # DELETE /users_cards/1.json
  def destroy
    @users_card.destroy
    respond_to do |format|
      format.html { redirect_to users_cards_url, notice: 'Users card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_card
      @users_card = UsersCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def users_card_params
      params.require(:users_card).permit(:user_id, :card_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base

	def index
		@users = User.all
	end

	def show
		@users = User.all
	end
 
	def edit
		@user = User.find(session[:id])
	end

	def update
		@user.update(userparams)
		redirect_to :back
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(userparams)
		if @user.save
			flash[:notice] = "Account successfully created!"
			redirect_to users_path
		else
			flash[:alert] = "User was not created successfully."
			redirect_to users_path
		end

			
	end


	def destroy
		if session[:id] == @user.id
			session[:id] = nil
			@user = User.find(params[:id]).destroy
			redirect_to users_path, notice: "User deleted!"
		else
			redirect_to users_path, notice: "User was not deleted."
		end
	end

	private

	def userparams
		params.require(:user).permit(:email, :password, :password_confirmation, :fname, :lname, :phone)
	end	


	def set_user
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_cards_helper.rb
module UsersCardsHelper
end

app/views/debits/_form.html.erb
<%= form_for @debit do |d| %>
	
	<%= d.label :cardnumber, "Card Number" %>
    <%= d.text_field :cardnumber, :required => true %>
    <br />
    <br />
    <%= d.label :expirationmonth, "Expiration Month" %>
    <%= d.text_field :expirationmonth, :required => true %> 
    <br />
    <br />
    <%= d.label :expirationyear, "Expiration Year" %>
    <%= d.password_field :expirationyear, :required => true %> 
    <br />
    <br />
    <%= d.submit %>

    <% end %>
</div>
  

app/views/debits/index.html.erb
<h3>Debit Indes page!</h3>

app/views/debits/new.html.erb
<h3> Create a New User! </h3>

<%= render 'form' %>
<br />
<%= link_to 'cancel', users_path %>

app/views/home/homepage.html.erb
<h3>This is my homepage!</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Mywallet</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<div id="flash">
			<%= flash[:notice] if flash[:notice] %>
		</div>

		<div id="alert">
			<%= flash[:alert] if flash[:alert] %>
		</div>

		<div id="container">
			<header>
				<div id="title">
					<h3>Wallet App</h3>
				</div>

			</header>

			<div id="content">
				<%= yield %>
			</div>

			<footer>
				<p> Kevin Kuoch Wallet App Footer
			</footer>
		</div>
	</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |n| %>

    <%= n.label :fname, "First Name" %>
    <%= n.text_field :fname, :required => true %>
    <br />
    <br />
    <%= n.label :lname, "Last Name" %>
    <%= n.text_field :lname, :required => true %> 
    <br />
    <br />
    <%= n.label :email, "Email" %>
    <%= n.text_field :email, :required => true %> 
    <br />
    <br />
    <%= n.label :password, "Password" %>
    <%= n.password_field :password, :required => true %> 
    <br />
    <br />
    <%= n.label :password_confirmation, "Password Confirmation" %>
    <%= n.password_field :password_confirmation, :required => true %> 
    <br />
    <br />
    <%= n.label :phone, "Phone" %>
    <%= n.password_field :phone %>
    <br />
    <br />
    <%= n.submit %>

    <% end %>
</div>
  

app/views/users/index.html.erb
<h3>User Index!</h3>

app/views/users/new.html.erb
<h3> Create a New User! </h3>

<%= render 'form' %>
<br />
<%= link_to 'cancel', users_path %>

app/views/users_cards/_form.html.erb
<%= form_for(@users_card) do |f| %>
  <% if @users_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@users_card.errors.count, "error") %> prohibited this users_card from being saved:</h2>

      <ul>
      <% @users_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :card_id %><br>
    <%= f.number_field :card_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users_cards/edit.html.erb
<h1>Editing Users Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @users_card %> |
<%= link_to 'Back', users_cards_path %>

app/views/users_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users Cards</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Card</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users_cards.each do |users_card| %>
      <tr>
        <td><%= users_card.user_id %></td>
        <td><%= users_card.card_id %></td>
        <td><%= link_to 'Show', users_card %></td>
        <td><%= link_to 'Edit', edit_users_card_path(users_card) %></td>
        <td><%= link_to 'Destroy', users_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users card', new_users_card_path %>

app/views/users_cards/new.html.erb
<h1>New Users Card</h1>

<%= render 'form' %>

<%= link_to 'Back', users_cards_path %>

app/views/users_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @users_card.user_id %>
</p>

<p>
  <strong>Card:</strong>
  <%= @users_card.card_id %>
</p>

<%= link_to 'Edit', edit_users_card_path(@users_card) %> |
<%= link_to 'Back', users_cards_path %>